[package]
name = "random_meta"
version = "0.1.0"
edition = "2021"

[lib]
name = "random_meta"
path = "src/lib.rs"

[dependencies]
rand = "0.9"
rayon = "1.10"
file_reader = { path = "../file_reader/" }
checker = { path =  "../checker" }
